# Generated by Django 4.1 on 2022-08-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='inn',
            field=models.CharField(max_length=14),
        ),
    ]
